apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ark160/apigateway:v6
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:80"

            # RabbitMQ (matches your docker-compose)
            - name: RABBITMQ_HOST
              value: "rabbitmq"

            - name: RABBITMQ_USER
              value: "guest"

            - name: RABBITMQ_PASSWORD
              value: "guest"

            - name: RABBITMQ_EXCHANGE
              value: "order.exchange"

            - name: RABBITMQ_ROUTINGKEY
              value: "order.created"